name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./AwesomeChatBot.DiscordWrapper.csproj
    - name: Build
      run: dotnet build ./AwesomeChatBot.DiscordWrapper.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test ./AwesomeChatBot.DiscordWrapper.csproj --no-restore --verbosity normal
