name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.301
    - name: Build
      run: dotnet build ./AwesomeChatBot.Discord.csproj --configuration Release
    - name: Test
      run: dotnet test ./AwesomeChatBot.Discord.csproj --no-restore --verbosity normal
